### ISSUE TITLE
Please release a new version -> JLab 4

### ISSUE THREAD

**Issue by jhgoebbert** [jupyterlab-contrib/jupyterlab-topbar#105]
Hello,
would it be possible to create a new official release of this extension - especially because much has changed compared to the last release version and also JupyterLab 4 is now supported.

**Comment by jtpio** [comment]
The packages should now be available: https://github.com/jupyterlab-contrib/jupyterlab-topbar/releases/tag/v1.0.0

Although there were some hiccups with the release process that will need to be fixed for the next releases: https://github.com/jupyterlab-contrib/jupyterlab-topbar/issues/113

**Comment by jhgoebbert** [comment]
Great. Thank you!
