### ISSUE TITLE
Theme toggler extension overriding body font

### ISSUE THREAD

**Issue by mahendrapaipuri** [jupyterlab-contrib/jupyterlab-topbar#124]
## Description

Theme toggler extension imports [blueprint CSS](https://github.com/jupyterlab-contrib/jupyterlab-topbar/blob/712f910064831e304db2e32fc1ea0f683467c563/packages/theme-toggler-extension/src/index.tsx#L7) used for the  `Switch` component. As extensions are imported _after_ the core JupyterLab, Blueprint CSS is _potentially_ overriding JupyterLab core CSS properties. One change that is quite visible is body font family.

Here is a screenshot of font with vanilla JupyterLab:
![jp_font](https://github.com/jupyterlab-contrib/jupyterlab-topbar/assets/44365948/517cf83f-a7b3-4a1f-865b-2691f03eb443)

Here is a screenshot with theme toggler extension installed:
![blueprint_font](https://github.com/jupyterlab-contrib/jupyterlab-topbar/assets/44365948/a04ec1b3-bbfe-4370-8471-6c25d470f2cf)

Ideally, we should make the blueprint CSS scoped to theme toggler component.

## Reproduce

Install `jupyterlab-theme-toggler==1.0.0` and notice the change in font family

## Expected behavior

Extension should not alter JupyterLab core CSS properties

@jtpio I have been trying to scope it to component without much success. Do you have any leads? One solution is to redeclare the `body` CSS class with "correct" font-family in `base.css`:

```
body {
  font-family: var(--jp-ui-font-family);
}
```
or re-importing core CSS using `import '@jupyterlab/application/style/core.css';` should override the blueprint CSS and bring back JupyterLab default font family. If we can scope the blueprint CSS to the theme toggler component, that would be the ideal solution though!

**Comment by jtpio** [comment]
Thanks @mahendrapaipuri for reporting :+1: 

Indeed, JupyterLab used to depend on Blueprint before which is why this extension reused the switch component from Blueprint.

Maybe we could switch to the Jupyter UI toolkit instead? https://jupyterlab-contrib.github.io/jupyter-ui-toolkit/?path=/docs/components-switch--documentation

**Comment by mahendrapaipuri** [comment]
Ah, nice! Didnt know about JupyterUI toolkit. I will it a go! Cheers @jtpio
