### ISSUE TITLE
Memory tab shown as 0 after installing system monitor extension

### ISSUE THREAD

**Issue by felihong** [jupyterlab-contrib/jupyterlab-topbar#36]
Hi there, 

thanks for the lovely extensions. 
I installed the monitor extension as described in the doc:
```
jupyter labextension install jupyterlab-system-monitor
pip install nbresuse
```

However the memory tab surfaced remains `0`:
![Screenshot 2020-02-05 at 13 32 15](https://user-images.githubusercontent.com/28823328/73841947-f16d2400-481b-11ea-89ad-00984689b541.png)

Some environments:
- JupyterLab `1.2.5`
- Notebook `6.0.3`
- Python `3.7.6`

Any ideas? Thanks.

**Comment by jtpio** [comment]
@Felihong is this still happening after configuring `nbresuse`? 

https://github.com/jtpio/jupyterlab-system-monitor#configuration

**Comment by Felihong** [comment]
Hi @jtpio , thanks for your reply. 

I edited the `~/.jupyter/jupyter_notebook_config.py` by adding:
```
c.NotebookApp.ResourceUseDisplay.mem_limit = Size_of_GB *1024*1024*1024
```
but the memory remains as before. And this happens in my notebook container running a GKE pod. 
However in my personal Mac the temporal memory usage is well presented which makes me confused.

**Comment by jtpio** [comment]
Was the file edited after the pod was started? Or is it mounted as a volume?

This would otherwise require a restart of the server.

**Comment by Felihong** [comment]
Yes I modified the config file after the server was launched:
```
cat jupyter_notebook_config.py| grep "mem_limit"
c.NotebookApp.ResourceUseDisplay.mem_limit = '0.1*1024*1024*1024'
```
Is a restart still required in this case?

**Comment by jtpio** [comment]
Yes. The other way would be to specify the `mem_limit` on the spawner (assuming the GKE pod is started with ZTJH), and nbresuse would pick it up: https://github.com/yuvipanda/nbresuse#memory-limit

But even without setting the limit there should be some value:

![image](https://user-images.githubusercontent.com/591645/74541854-b6b56b00-4f42-11ea-95fe-6ef95fa936a0.png)

**Comment by jtpio** [comment]
Closing as this should be addressed in the `jupyter-resource-usage` repo, maybe as part of https://github.com/jupyter-server/jupyter-resource-usage/issues/191.
