### ISSUE TITLE
Jupyterlab V3

### ISSUE THREAD

**Issue by Jacques2101** [jupyterlab-contrib/jupyterlab-topbar#55]
I updated Jupyterlab to 3.01 Version in a new env. 
I reinstall topbar ext with: 
```
# container extension
pip install jupyterlab-topbar

# to install the topbar-text extension
jupyter labextension install jupyterlab-topbar-text
```

I don't see as usual the top bar the logout button.  

Thx for your help.

**Comment by jtpio** [comment]
Thanks @Jacques2101.

The logout button extension needs to be installed separately:

```
pip install jupyterlab-logout
```

**Comment by jtpio** [comment]
Closing as answered. Feel free to reopen or open a new issue if you still have problems, thanks!
