### ISSUE TITLE
Option to remove separator lines

### ISSUE THREAD

**Issue by xeliba** [jupyterlab-contrib/jupyterlab-topbar#68]
Many thanks for this nice extension!

I have a request for an aesthetic improvement. Is there an easy way to remove those separator lines?
![example png](https://user-images.githubusercontent.com/18423286/124771303-4f36fb80-df3b-11eb-8bf4-c35b387dbefe.jpg)

In my use case, I only want to add the Logout button, and this does not need to be draggable, so that the separator lines just look somewhat disturbing.

**Comment by xeliba** [comment]
I realized this is possible by adapting the CSS style file in `packages/jupyterlab-topbar/style/index.css` on line 17
```
@@ -14,7 +14,7 @@
   display: flex;
   flex-direction: column;
   justify-content: center;
-  border-left: calc(var(--jp-border-width) * 2) solid var(--jp-border-color0);
+  border-left: calc(var(--jp-border-width) * 2) solid var(--jp-layout-color1);
   padding-left: 5px !important;
   padding-right: 5px !important;
 }
 ```
But maybe it's worth putting this into an option?

**Comment by jtpio** [comment]
Thanks @xeliba.

These delimiters were initially placed to hint users the items can be moved via drag and drop. Maybe we could indeed remove them, and use a cursor mouse pointer instead.

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/jupyterlab-contrib/jupyterlab-topbar/pull/92, which dropped the separator lines:

![image](https://github.com/jupyterlab-contrib/jupyterlab-topbar/assets/591645/5705f2ac-2aac-436d-ac02-7c043ca3f8d3)
