### ISSUE TITLE
Deprecate the extension for JupyterLab 4.0

### ISSUE THREAD

**Issue by jtpio** [jupyterlab-contrib/jupyterlab-topbar#81]
JupyterLab 4.0 will have support for customizing top bar items via the settings: https://github.com/jupyterlab/jupyterlab/pull/12586

We should then deprecate this extension, and link to the JupyterLab documentation.

After JupyterLab 4.0 is released, we can then archive this repository as well.

**Comment by mahendrapaipuri** [comment]
@jtpio I have been trying to migrate these extensions to JupyterLab 4 without a lot of luck. For simple commands, I noticed that I can define my custom commands and then  add it to `TopBar` settings as 

```
"jupyter.lab.toolbars": {
    "TopBar": [
      {
        "name": "Custom Command",
        "command": "mycustomnamespace:my-custom-command",
        "rank": 1000
      }
    ]
  },

```

But how can I add widgets to `TopBar` toolbar? For instance, if I want to migrate [theme-toggler](https://github.com/jtpio/jupyterlab-theme-toggle), how can I add the React Widget to the `TopBar` toolbar? Any help would be appreciated. Cheers!!

**Comment by jtpio** [comment]
Thanks @mahendrapaipuri.

Maybe we could try to have a look at https://github.com/jtpio/jupyterlab-theme-toggle to migrate the extension to JupyterLab 4, which would serve as a good example?

**Comment by jtpio** [comment]
Just opened https://github.com/jtpio/jupyterlab-theme-toggle/issues/22

**Comment by mahendrapaipuri** [comment]
Cheers @jtpio for coming back. I have been trying to do exactly the same thing. Just to give you a bit of the context, I have created [few topbar buttons](https://gitlab.com/idris-cnrs/jupyter/jupyterlab/jupyterlab-toolbar-buttons/-/blob/jl_4_hatchling/packages/jupyterlab-toolbar-buttons/src/index.ts) which are simple hyperlinks like Logout button. And defining them in [settings](https://gitlab.com/idris-cnrs/jupyter/jupyterlab/jupyterlab-toolbar-buttons/-/blob/jl_4_hatchling/packages/jupyterlab-toolbar-buttons/schema/plugin.json) will render these buttons neatly in the JupyterLab.

The theme-toggler that you did is effectively a `Switch` widget and you are [adding that widget](https://github.com/jtpio/jupyterlab-theme-toggle/blob/c100401a4ad4ff3c5e7392f1eefcad64103198e5/src/index.tsx#L102-L114) to `topbar` explicitly. The thing that is not clear for me how can we add this widget to the new `topbar` extension? From my understanding, the new `topbar` extension execute commands and render either a name or icon in the frontend. The theme-toggler, however, is an interactive widget and I am not able to figure out how can I add it to the `topbar`!!

**Comment by jtpio** [comment]
Thanks @mahendrapaipuri for looking into this!

I think a good example would be the checkpoint indicator in Notebook 7:


A plugin defines a new toolbar factory called `checkpoint` here: https://github.com/jupyter/notebook/blob/33a383d3f857b4de0da10892121de7bd4d932162/packages/notebook-extension/src/index.ts#L83-L90

Which is then used here: https://github.com/jupyter/notebook/blob/33a383d3f857b4de0da10892121de7bd4d932162/packages/notebook-extension/schema/checkpoints.json#L4-L6

For the theme toggle extension, the toolbar factory would return the `Switch` widget.

**Comment by mahendrapaipuri** [comment]
Sweet! Cheers @jtpio. I will look into that example and try to implement theme toggler and let you know. Thanks again!!

**Comment by mahendrapaipuri** [comment]
@jtpio Worked beautifully. Cheers! I will put up a PR in theme-toggler repo soonish. 

Do you think we can create a monorepo for [topbar-text](https://github.com/jupyterlab-contrib/jupyterlab-topbar-text), [logout-button](https://github.com/jupyterlab-contrib/jupyterlab-logout) and [theme-toggler](https://github.com/jtpio/jupyterlab-theme-toggle) as they are very similar?

**Comment by mahendrapaipuri** [comment]
Alright. I will work on it in the coming weeks. Would you create a new repo to host these extensions or use an existing one?

**Comment by mahendrapaipuri** [comment]
I agree, that makes sense. Cheers @jtpio for the help. I will work on the PR.

**Comment by jtpio** [comment]
That would be perfect, thanks again!
